name = "swr-do"
route = { pattern = "*/*", zone_name = "swr.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
 
kv_namespaces = [
  { binding = "STORAGE", id = "9e6af3c00d3540f5875ff0a112f2675c" }
]

[miniflare]
cache = true
cache_persist = "./data/"
kv_persist = "./data/"

[build.upload]
format = "modules"

[miniflare.mounts]
ctx-do = "../ctx.do"